# version: '27.3'

services:
  backend:
    build: ./app/backend
    ports:
      - "5001:5001"
      - "5678:5678" #debubpy port

    environment:
      - FLASK_ENV=development
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/${MYSQL_DATABASE}
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
        - ./app/backend:/app/
        - ./docker_scripts:/scripts


  frontend:
    build: 
      context: ./app/frontend
      dockerfile: Dockerfile
    container_name: frontend
    # restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./app/frontend:/app
      - /app/node_modules
    environment:
      - VITE_APP_BACKEND_ADDRESS=http://backend:5001
    # networks:
    #   - network
    depends_on:
      - backend
    command: npm run dev

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"                      # Expose MySQL port for local access
    volumes:
      - mysql_data:/var/lib/mysql        # Volume for persistent data
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:

